name: Sync develop with master
#on:
#  push:
#    branches:
#      - master
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: "*/5 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "merge-branch"
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Merging branches
        uses: safinazward/merge-branch@1.0.3

        with:
          source_branch: master
          target_branch: develop
          github_token: ${{secrets.GITHUB_TOKEN}}
          commit_message: "merge branch master into develop"